export const dummy = [
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    amount: 100.0,
    date: "2022-01-01",
    status: "pending",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "janesmith@example.com",
    amount: 200.0,
    date: "2022-01-05",
    status: "paid",
  },
  {
    id: 3,
    name: "Bob Johnson",
    email: "bobjohnson@example.com",
    amount: 50.0,
    date: "2022-01-10",
    status: "pending",
  },
  {
    id: 4,
    name: "Alice Brown",
    email: "alicebrown@example.com",
    amount: 300.0,
    date: "2022-01-15",
    status: "paid",
  },
  {
    id: 5,
    name: "Mike Davis",
    email: "mikedavis@example.com",
    amount: 250.0,
    date: "2022-01-20",
    status: "pending",
  },
  {
    id: 6,
    name: "Emily Taylor",
    email: "emilytaylor@example.com",
    amount: 400.0,
    date: "2022-01-25",
    status: "paid",
  },
  {
    id: 7,
    name: "Sarah Lee",
    email: "sarahlee@example.com",
    amount: 150.0,
    date: "2022-02-01",
    status: "pending",
  },
  {
    id: 8,
    name: "Kevin White",
    email: "kevinwhite@example.com",
    amount: 350.0,
    date: "2022-02-05",
    status: "paid",
  },
  {
    id: 9,
    name: "Lisa Nguyen",
    email: "lisanguyen@example.com",
    amount: 200.0,
    date: "2022-02-10",
    status: "pending",
  },
  {
    id: 10,
    name: "David Kim",
    email: "davidkim@example.com",
    amount: 450.0,
    date: "2022-02-15",
    status: "paid",
  },
  {
    id: 11,
    name: "Olivia Martin",
    email: "oliviamartin@example.com",
    amount: 100.0,
    date: "2022-02-20",
    status: "pending",
  },
  {
    id: 12,
    name: "Benjamin Hall",
    email: "benjaminhall@example.com",
    amount: 300.0,
    date: "2022-02-25",
    status: "paid",
  },
  {
    id: 13,
    name: "Hannah Patel",
    email: "hannahpatel@example.com",
    amount: 250.0,
    date: "2022-03-01",
    status: "pending",
  },
  {
    id: 14,
    name: "Ethan Walker",
    email: "ethanwalker@example.com",
    amount: 400.0,
    date: "2022-03-05",
    status: "paid",
  },
  {
    id: 15,
    name: "Isabella Garcia",
    email: "isabellagarcia@example.com",
    amount: 150.0,
    date: "2022-03-10",
    status: "pending",
  },
  {
    id: 16,
    name: "Julia Brooks",
    email: "juliabrooks@example.com",
    amount: 350.0,
    date: "2022-03-15",
    status: "paid",
  },
  {
    id: 17,
    name: "Alexander Brown",
    email: "alexanderbrown@example.com",
    amount: 200.0,
    date: "2022-03-20",
    status: "pending",
  },
];